name: Build OpenFAST Debug EXE

on:
  workflow_dispatch:

env:
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/3a871580-f839-46ed-aeae-685084127279/intel-oneapi-hpc-toolkit-2025.3.0.378_offline.exe
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/1f18901e-877d-469d-a41a-a10f11b39336/intel-oneapi-base-toolkit-2025.3.0.372_offline.exe
  VS_VER: 2022

jobs:
  build-debug:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Cache Intel oneAPI
        id: cache-oneapi
        uses: actions/cache@v4
        with:
          path: |
            C:\Program Files (x86)\Intel\oneAPI\setvars-vcvarsall.bat
            C:\Program Files (x86)\Intel\oneAPI\compiler
            C:\Program Files (x86)\Intel\oneAPI\mkl
          key: oneapi-win-fortran-mkl-2025.3.0

      - name: Install Intel oneAPI Fortran Compiler
        if: steps.cache-oneapi.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl.exe --output "%TEMP%\hpckit.exe" --url "%WINDOWS_HPCKIT_URL%" --retry 5 --retry-delay 5
          start /b /wait "%TEMP%\hpckit.exe" -s -x -f hpckit_extracted --log extract_hpc.log
          del "%TEMP%\hpckit.exe"
          hpckit_extracted\bootstrapper.exe -s --action install --components=intel.oneapi.win.ifort-compiler --eula=accept -p=NEED_VS2017_INTEGRATION=0 -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=0 --log-dir=.
          rd /s/q "hpckit_extracted"

      - name: Install Intel oneAPI MKL
        if: steps.cache-oneapi.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl.exe --output "%TEMP%\basekit.exe" --url "%WINDOWS_BASEKIT_URL%" --retry 5 --retry-delay 5
          start /b /wait "%TEMP%\basekit.exe" -s -x -f basekit_extracted --log extract_base.log
          del "%TEMP%\basekit.exe"
          basekit_extracted\bootstrapper.exe -s --action install --components=intel.oneapi.win.mkl.devel --eula=accept -p=NEED_VS2017_INTEGRATION=0 -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=0 --log-dir=.
          rd /s/q "basekit_extracted"

      - name: Build Debug OpenFAST
        shell: cmd
        run: |
          call .github\scripts\build_windows_executables.bat

      - name: Upload Debug EXE
        uses: actions/upload-artifact@v4
        with:
          name: openfast-debug
          path: build/bin/*.exe
