name: Build OpenFAST Debug EXE

on:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Install Intel oneAPI Fortran
        uses: modflowpy/install-intelfortran-action@v1
        with:
          compiler-variant: intel-classic
          architecture: intel64

      - name: Build Debug OpenFAST
        shell: cmd
        run: |
          devenv vs-build/OpenFAST.sln /Build "Debug|x64"

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: openfast-debug
          path: build/bin/*.exe
